// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJTfGdmrLYd8EEbyaD7wsjZ2wYg5-qek',
    appId: '1:531174116492:web:e790cff0ff498609633fa9',
    messagingSenderId: '531174116492',
    projectId: 'whatsapp-backend-233fb',
    authDomain: 'whatsapp-backend-233fb.firebaseapp.com',
    storageBucket: 'whatsapp-backend-233fb.appspot.com',
    measurementId: 'G-WWRFNTNX37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXXEnNWtuYKj4NVB3JLnyVbDA0Y14W14',
    appId: '1:531174116492:android:920d1e7e21438a39633fa9',
    messagingSenderId: '531174116492',
    projectId: 'whatsapp-backend-233fb',
    storageBucket: 'whatsapp-backend-233fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqHkvaSB3kk2-6pPWa0_IFd3CXcOh9OQw',
    appId: '1:531174116492:ios:7c2fe0f831e134cc633fa9',
    messagingSenderId: '531174116492',
    projectId: 'whatsapp-backend-233fb',
    storageBucket: 'whatsapp-backend-233fb.appspot.com',
    iosClientId: '531174116492-e1dtoufsu7gaurhba0agjs08bkdnggr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
